### ISSUE TITLE
TextButton onClick support?

### ISSUE THREAD

**Issue by Nightsunnv** [ffAudio/foleys_gui_magic#108]
I'm trying to bind a file selecting function to a TextButton generated by Toolbox. But it seems like that there exists no such way. Further more, how could I bind a common function with the TextButton just like the way I bind the variables with the sliders? Looking forward to anyone's help, thx!

**Comment by ffAudio** [comment]
Hi, thank you for using foleys_gui_magic.

The function you are triggering has to live in the processor, therefore the magicState is the place to put it. It is then exposed under an ID you give it and you can select it in the TextButton.

An example can be found in the FoleysSynth:
https://github.com/ffAudio/foleys_gui_magic/blob/main/Examples/FoleysSynth/Source/PluginProcessor.cpp#L56

```
magicState.addTrigger ("triggerName",
    [processor]()
    {
        processor.doWhatever();
    });
```

Let me know if that works

**Comment by Nightsunnv** [comment]
That really helps! But may I ask one more question? Many commercial plugins can change their GUI at runtime, i.e., set some GUI elements to unvisible/visible after pressing a button or selecting a choice of combobox, etc. Could I make it with foleys_gui_magic?

**Comment by ffAudio** [comment]
Glad I could help.
There is a way to toggle things on and off.
If it is just visibility, you can have a look at the EqualizerExample:
You'll see two ToggleButtons, that switch the input and output analyser on and off.
- For that purpose create a property in the state. 
- The ToggleButton then references that property.
- The element you want to hide has a "visible" property, where you enter the same property again.

Another way is using the style classes, they also have a property to enable/disable the settings of that class.
For a responsive layout you then set the flex value to become zero with the class, and the object will vanish making space in the layout when the property becomes true.

**Comment by Nightsunnv** [comment]
Thank for your help! It was indeed set to "unvisible" after I did so.
Embarrassingly, howerver, I have misunderstood the meaning of "visibility". What I really want to achieve might be to load the GUI XML at runtime without the FOLEYS_SHOW_GUI_EDITOR_PALLETTE setting. To make a component disappear, I just set it's max-width or max-height to 0 when toolbox is on. But how could I do it when there's no toolbox?
Sorry for bothering. I've tried the magicState.setGuiValueTree() function but then I got an jassert error in juce::AudioProcessorParameter::endChangeGesture().
```
void AudioProcessorParameter::endChangeGesture()
{
    // This method can't be used until the parameter has been attached to a processor!
    jassert (processor != nullptr && parameterIndex >= 0);

   #if JUCE_DEBUG && ! JUCE_DISABLE_AUDIOPROCESSOR_BEGIN_END_GESTURE_CHECKING
    // This means you've called endChangeGesture without having previously
    // called beginChangeGesture. That might be fine in most hosts, but it
    // would be better to keep the calls matched correctly.
    jassert (isPerformingGesture);
    isPerformingGesture = false;
   #endif

    ScopedLock lock (listenerLock);

    for (int i = listeners.size(); --i >= 0;)
        if (auto* l = listeners[i])
            l->parameterGestureChanged (getParameterIndex(), false);

    if (processor != nullptr && parameterIndex >= 0)
    {
        // audioProcessorParameterChangeGestureEnd callbacks will shortly be deprecated and
        // this code will be removed.
        for (int i = processor->listeners.size(); --i >= 0;)
            if (auto* l = processor->listeners[i])
                l->audioProcessorParameterChangeGestureEnd (processor, getParameterIndex());
    }
}
```
This seems that the processor was down after setting the gui tree, or at least for a while (but it was enough to cause this error...). And I saw stateWasReloaded() function in class Toolbox.
```
void ToolBox::loadGUI (const juce::File& xmlFile)
{
    juce::FileInputStream stream (xmlFile);
    auto tree = juce::ValueTree::fromXml (stream.readEntireStreamAsString());

    if (tree.isValid() && tree.getType() == IDs::magic)
    {
        builder.getMagicState().setGuiValueTree (tree);
        stateWasReloaded();
    }

    setLastLocation (xmlFile);
}
```
It's a bit extremely difficult for me to transplant it to my processor, can you help me?

**Comment by Nightsunnv** [comment]
Thank you very much for your help! 
However, embarrassingly, I misunderstood the meaning of 'visible'. 
Now I need to change the XML used by the GUI when the combobox is changed (mouse click), which seems impossible to achieve. Currently, I switch the GUI style by selecting the index of the combobox and then clicking a button, but obviously it's not a good solution. But once I bind loadGUI function to the combobox, the program will raise jassert.
'''
void AudioProcessorParameter::endChangeGesture()
{
    // This method can't be used until the parameter has been attached to a processor!
    jassert (processor != nullptr && parameterIndex >= 0);

   #if JUCE_DEBUG && ! JUCE_DISABLE_AUDIOPROCESSOR_BEGIN_END_GESTURE_CHECKING
    // This means you've called endChangeGesture without having previously
    // called beginChangeGesture. That might be fine in most hosts, but it
    // would be better to keep the calls matched correctly.
    jassert (isPerformingGesture);
    isPerformingGesture = false;
   #endif

    ScopedLock lock (listenerLock);

    for (int i = listeners.size(); --i >= 0;)
        if (auto* l = listeners[i])
            l->parameterGestureChanged (getParameterIndex(), false);

    if (processor != nullptr && parameterIndex >= 0)
    {
        // audioProcessorParameterChangeGestureEnd callbacks will shortly be deprecated and
        // this code will be removed.
        for (int i = processor->listeners.size(); --i >= 0;)
            if (auto* l = processor->listeners[i])
                l->audioProcessorParameterChangeGestureEnd (processor, getParameterIndex());
    }
}
'''
It seems like GUI change has some conflicts with parameter change.
I've tried using loadGUI in audio loop, but juce prevented this with a mutex. 
Do you have any ideas?

**Comment by Nightsunnv** [comment]
Thanks a lot for your generous help! I finally used loadGUI function from toolbox with juce::Timer(to avoid juce's mutex on GUI), and set guiEditorPallete to unvisible in release building mode. It's an ugly solution, but it works. :)
