### ISSUE TITLE
xyDragComponent, return to default

### ISSUE THREAD

**Issue by Werner88** [ffAudio/foleys_gui_magic#37]
(Mac, XCode 10.1, Standalone-Build)
1)
in 1.10 here the xyDragComponent never paints the parameters.
When bringing the old code back to line 410 in foleysMagicJuceFactories.cpp
it works again:
instead of just //return std::unique_ptr<XYDragComponent>();
```
                         if (auto* magicState = getProcessorState())
                         {
                             auto item = std::make_unique<XYDragComponent>(magicState->getValueTreeState());
                             
                             auto paramX = config.getProperty (IDs::parameterX).toString();
                             if (paramX.isNotEmpty())
                                 item->setParameterX (paramX);
                             
                             auto paramY = config.getProperty (IDs::parameterY).toString();
                             if (paramY.isNotEmpty())
                                 item->setParameterY (paramY);
                             
                             return std::move (item);
                         }
                         else
                         {
                             return std::unique_ptr<XYDragComponent>();
                         }
```
                      
                      
2)
if a colourSelect field "x"-Button  in the Editor-Tool is not editable, and you change the fields value (set a new colour), after that you are not able to return to the default value, because the "x" Button is still not enabled. After selecting another node and coming back the "x" Button is enabled and you can return to the default value.

**Comment by ffAudio** [comment]
Thank you so much, yes that was a careless simplification.
Will fix that asap.

The second will be a bit more tricky to get right, I will look into it as well.

**Comment by ffAudio** [comment]
The XYDragger is fixed in Version 1.1.1. Resetting to default you need to use the workaround for now, I will try to improve things soon.

**Comment by ffAudio** [comment]
I found the reason why it wouldn't go back to default. If there is no value to look up in the stylesheet, it will skip setting, leaving the last setting.
I will have to consider either having a default value for everything or destroy the components and recreate them from scratch (probably the safer solution).

**Comment by ffAudio** [comment]
There is a refresh button in the menu that will recreate the GUI from scratch, in case such an undefined property keeps a previous editing state.
BTW. when running the GUI this cannot occur, it is just an issue during editing.

Since setting the property is handled in the wrapper, there is no way to generally avoid that situation.
