### ISSUE TITLE
Tabs don't appear until a resize / repaint occurs.

### ISSUE THREAD

**Issue by Normalised** [ffAudio/foleys_gui_magic#45]
My root node container has the display property set to 'tabbed' but the tabs themselves dont appear in the UI until I resize the window.

**Comment by ffAudio** [comment]
Thank you for the feedback. Unfortunatelly I cannot reproduce this here. I tried the master as well as the develop branch.

Did you mean it doesn't switch when editing it? Or when closing and reopening the PluginEditor?

Also which OS and which host are you trying?
I tested the FoleysSynth example as standalone on OSX 10.14. I would like to get to the bottom of this.
And if you can, please send me your xml file, maybe that gives a clue

**Comment by Normalised** [comment]
I'm running against the develop branch here.
OS is Windows 10. Tested in Standalone and Bitwig.
It only happens on first launch of the editor in plugin mode. If the editor is closed and re-opened the tabs are still visible.

I can't really share my full UI xml but i'm trying to create a minimal example for testing.

At the moment the tabs are working fine in the most basic setup :

`<?xml version="1.0" encoding="UTF-8"?>

<magic>
  <Styles>
    <Style name="default">
      <Nodes/>
      <Classes>
        <plot-view border="2" background-color="black" border-color="silver" display="contents"/>
        <nomargin margin="0" padding="0" border="0"/>
        <group margin="5" padding="5" border="2" flex-direction="column"/>
      </Classes>
      <Types>
        <Slider border="0" slider-textbox="textbox-below"/>
        <ToggleButton border="0" max-height="50" caption-size="0" text="Active"/>
        <TextButton border="0" max-height="50" caption-size="0"/>
        <ComboBox border="0" max-height="50" caption-size="0"/>
        <Plot border="0" margin="0" padding="0" background-color="00000000"
              radius="0"/>
        <XYDragComponent border="0" margin="0" padding="0" background-color="00000000"
                         radius="0"/>
      </Types>
    </Style>
  </Styles>
  <View id="root" display="tabbed">
    <View/>
  </View>
</magic>`

So i'll work my way from here upwards, see when it stops working and get back to you.

**Comment by ffAudio** [comment]
Awesome. I will try with an empty project meanwhile, maybe that is the difference...

**Comment by Normalised** [comment]
This might help, if I choose 'Load XML' in either the test or main project and load that basic XML above, then the tabs are not visible until i resize.

But weirdly the full XML loaded via Binary Data in the test project is showing tabs on first open.

**Comment by ffAudio** [comment]
Thanks, I think that should help me track it down.

**Comment by ffAudio** [comment]
That's interesting, I found this, which looks like a merge mistake:
https://github.com/ffAudio/foleys_gui_magic/blob/develop/General/foleys_MagicGUIBuilder.cpp#L72
By removing these two lines it works here. Can you try if that fixes your error as well?

I think those various updateXYZ methods are due for an overhaul...

**Comment by Normalised** [comment]
Yep, thats it. Works as expected now in standalone and plugin. Thanks.
