### ISSUE TITLE
Dealing with Sound Artificats, Static, Popping when changing Gain Values with Sliders

### ISSUE THREAD

**Issue by r00tk1ll** [ffAudio/foleys_gui_magic#67]
I have a general question about the best way to deal with unwanted clicking/popping noises when using GUI Magic in a JUCE project.

I have started a simple project based off of your Equalizer Example, the JUCE ASIO driver and a Scarlett Interface (nothing fancy just plugging a guitar in and testing).

The first thing I notice when adjusting the output slider either way while audio is playing are Sound Artifacts as clicks and pops. I have read and watch videos where this is addressed by implementing Gain Ramps. So before getting to involved in this project, I was wondering what the recommended way of handling this would be?

Most of the examples I see for JUCE use a native GUI or something like GenericAudioProcessorEditor. Is there anything specific related to GUI Magic I should research or should I approach just like any standard JUCE project?

Thanks for your help

**Comment by ffAudio** [comment]
This is indeed not in the scope of PGM. The examples in the PluginGuiMagic repository are meant to showcase the features of the foleys_finest_module and with the EqualizerExample I challenged myself to allow all features of my older open source Frequalizer in a non-developer customizable way. I think so far I succeeded ;-)

To come to your actual issue:
The EqualizerExample uses the juce::dsp::ProcessorChain and in that a juce::dsp::Gain processor. That has a juce::SmoothedValue built in which is a more advanced method than the ramps you mentioned.

The juce::SmoothedValue have a setting where you can limit the speed of changes. That is a huge change could be spread over multiple blocks, while using the gain ramp will make a ramp as steep as necessary to achieve the target value within one block. If the block size is small this can mean drastic changes in short time.

So far I didn't experience the sound artefacts you mention. But the example has no parameter smoothing for the filters, so quick changes in the filter parameters (especially frequency) could indeed introduce such artefacts.

**Comment by r00tk1ll** [comment]
Thank you for the explanation on this subject, that makes perfect sense and is actually the best case scenario for those of us new to PGM and JUCE in general. Keeping the Graphics and Audio Processing independent of one another as much as possible makes it much easier to grasp the concepts and troubleshoot issues in general.

After some experimentation I found that simply adding this line to the constructor cleared up the noise for me, maybe this will help someone in the future:

`filter.get<0>().setRampDurationSeconds(0.05);`
