### ISSUE TITLE
ComboBox Not Displaying Selected Value

### ISSUE THREAD

**Issue by r00tk1ll** [ffAudio/foleys_gui_magic#72]
I'm sure there is something wrong in my configuration but I can't seem to get the combo box to display the selected value.

I.E. In the Equalizer Example the Filter Type combo box/drop down menu displays the name of the selected item.

![image](https://user-images.githubusercontent.com/12835789/147907172-fd3237ae-c8f9-4cbc-b1d0-86c445ebc020.png)

Does the combo box function like this by default or is there something else I need to configure to get my combo boxes to show their selected values?

**Comment by ffAudio** [comment]
Are you using the ComboBox of PGM or do you wrap your own ComboBox?
You shouldn't need to do anything if you use the ComboBox of PGM. It relies on this line:

https://github.com/ffAudio/foleys_gui_magic/blob/main/General/foleys_MagicJUCEFactories.cpp#L223

If you used an AudioParameterChoice, this JUCE function will return the possible options as strings and those will be used to fill the ComboBox. 
I think for other parameter types it will try to convert the numeric values to String, but IIRC there was a limit when this is ignored, since e.g. for a continuous float parameter a ComboBox would probably burst.

Does that help?

**Comment by r00tk1ll** [comment]
Thanks for the quick reply, I added all the combo boxes by dragging and dropping via the FGM interface. 

I.E.
![Capture](https://user-images.githubusercontent.com/12835789/148024777-ef66ab57-8836-4b6c-9a09-bc6ee61fa1a5.PNG)

On the backend I create a parameter layout with an AudioParameterChoice that is assigned a String array like this:

`juce::StringArray presetMenuValues =
{
    "Presets",
    "Choice1",
    "Choice2",
    "Choice3",
    "Choice4",
    "Choice5"
};

    //preset menu values
    auto presetMenu = std::make_unique<juce::AudioParameterChoice>(IDs::presetMenu,
        "Presets",
        presetMenuValues,
        0);
`
It looks like I'm missing the update portion you linked to above but just wanted to double check with you on that.

**Comment by r00tk1ll** [comment]
Okay so after further testing with my scenario I am still unable to get the combo created with FGM to display the selected values. Here are some screenshots of what I'm seeing, is it possible the combo box is displaying a value but it somehow hidden underneath a layer? 

Just brainstorming any other ideas I could test? Do the elements in the GUI have attributes like CSS? I.E. visibility, z-index, etc?

![1](https://user-images.githubusercontent.com/12835789/148335462-18e3161b-c334-4c69-a63b-3adda1fb7a48.png)
![3](https://user-images.githubusercontent.com/12835789/148335465-bef14c12-eafa-419d-8de9-595bd7706012.png)

**Comment by r00tk1ll** [comment]
I figured it out, if anyone else runs into this I had to clear the combo-text field out by clicking the red x 3 times. Then reassign the color value.

![1](https://user-images.githubusercontent.com/12835789/148635120-653a61d2-788a-497e-949f-a3e13ebf20a8.PNG)
![2](https://user-images.githubusercontent.com/12835789/148635121-8a53ba16-b265-488b-bd74-3cab0828b1e8.PNG)
![3](https://user-images.githubusercontent.com/12835789/148635122-b7603a4a-f015-417a-9347-08746ae1f92a.PNG)
